const COUNTER_ADD = "COUNTER_ADD";
const COUNTER_DECREASE = "COUNTER_DECREASE";
const SET_USERS = "SET_USERS";
const SET_USERS_LOADING_STATUS = "SET_USERS_LOADING_STATUS";

export default {
  COUNTER_ADD,
  COUNTER_DECREASE,
  SET_USERS,
  SET_USERS_LOADING_STATUS
};
